[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nina_v2 = "BmdryooV1qzhH3auE8xSzxTD97A83i5Xqxw1viRP73rv"
orp = "FUnmsBnsTDEsa5zTcUJixVzwPZZwXNNfmp5ECr2acbYd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/michaelpollard/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build && mv ./target/idl/nina_v2.json ./target/idl/nina_v_2.json" 