[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
nina_v2 = "nina2DQvAA8Sa9rxG72swBcNNDYQxdWGojzwDk9yn2q"

[programs.devnet]
nina_v2 = "nina2DQvAA8Sa9rxG72swBcNNDYQxdWGojzwDk9yn2q"

[programs.mainnet]
nina_v2 = "nina2DQvAA8Sa9rxG72swBcNNDYQxdWGojzwDk9yn2q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/michaelpollard/.config/solana/nina.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
build = "anchor build && mv ./target/idl/nina_v2.json ./target/idl/nina_v_2.json" 